name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
        
      - name: Install dependencies
        run: |
          poetry install

      - name: Setup environment variables
        run: |
          echo "PYTHONPATH=src" >> $GITHUB_ENV
          echo "ENV_VAR=${{ vars.ENV_VAR }}" >> $GITHUB_ENV
          echo "SECRET_VAR=${{ secrets.SECRET_VAR }}" >> $GITHUB_ENV
      
      - name: Run tests
        run: |
            poetry run pytest
